name: Dependabot Auto-Merge

on:
  # pull_request_target:
  workflow_call:
    inputs:
      pr_url:
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.event_name == 'workflow_call' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ github.event_name == 'workflow_call' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ inputs.pr_url || github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}