name: NPM Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  npm-validate:
    name: auto_merge_npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd npm && npm install
      - name: Validate package
        run: cd npm && node -e "require('./index.js')"